on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: contanerregisteryname.azurecr.io
        username: ${{ secrets.acr_contanerregisteryname_username }}
        password: ${{ secrets.acr_contanerregisteryname_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/spring-boot-docker" -f  "spring-boot-docker/Dockerfile" -t contanerregisteryname.azurecr.io/kubernitiesname:${{ github.sha }}
        docker push contanerregisteryname.azurecr.io/kubernitiesname:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kubernitiesname_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kubernitiesnamefcfc | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kubernitiesnamefcfc`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kubernitiesnamefcfc
        container-registry-url: contanerregisteryname.azurecr.io
        container-registry-username: ${{ secrets.acr_contanerregisteryname_username }}
        container-registry-password: ${{ secrets.acr_contanerregisteryname_password }}
        secret-name: kubernitiesndockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: kubernitiesnamefcfc
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          contanerregisteryname.azurecr.io/kubernitiesname:${{ github.sha }}
        imagepullsecrets: |
          kubernitiesndockerauth